### ISSUE TITLE
Update modules to support units/coordinates

### ISSUE THREAD

**Issue by ianmackenzie** [ianmackenzie/elm-geometry#86]
The update discussed in #66 is now underway in the [`coordinate-systems`](/ianmackenzie/elm-geometry/tree/coordinate-systems) branch. Pull requests are welcome to help update more modules! In most cases it's relatively straightforward but there are quite a few modules to update.

The general process is:

  - Change type signatures from (for example) `LineSegment3d` to `LineSegment3d units coordinates`. Note that `relativeTo` and `placeIn` functions have slightly unusual signatures since they involve conversions between different coordinate systems - look at some of the existing diffs for examples.
  - Change most raw `Float`s in type signatures to `Quantity Float units`, with a couple of exceptions: scaling factors in functions like `scaleAbout` remain as `Float`s (since scaling factors are unitless), certain quantities like squared distances or areas are `Quantity Float (Squared units)` instead, and rotation angles are `Angle` values.
  - Where function implementations currently work with raw `Float` values (using `+`, `-`, `min`, `max`, `abs` etc.), change those to use the corresponding `Quantity` functions (`Quantity.plus`, `Quantity.min`, `Quantity.abs` etc.) where appropriate.

I've updated many of the 2D modules already, so many of those diffs can be used as examples. The low-level point/vector/direction types generally take the most work as they do quite a lot with `Float` values; for higher-level types it is mostly just a matter of updating type signatures. See for example [the `Point2d` update](https://github.com/ianmackenzie/elm-geometry/commit/171b5713f9fa605ad89331d7a8645a952df1fb07) vs [the `Triangle2d` update](https://github.com/ianmackenzie/elm-geometry/commit/cc1204c10984f55336b221c7df5b069e4568f64b).

I'll continue working on the remaining 2D modules for now - leave a comment in this issue if you're planning to tackle one or more of the 3D modules, so we can avoid duplicate work. I'll keep track of here of which modules have been claimed:

- [x] `Arc3d`
- [x] `Axis3d`
- [x] `BoundingBox3d`
- [x] `Circle3d`
- [x] `CubicSpline3d`
- [x] `Direction3d`
- [x] `Ellipse2d`
- [x] `EllipticalArc2d`
- [x] `Frame3d`
- [x] `LineSegment3d`
- [x] `Plane3d` (no 2D equivalent)
- [x] `Point3d`
- [x] `Polyline3d`
- [x] `QuadraticSpline3d`
- [x] `Rectangle2d`
- [x] `SketchPlane3d` (I'll take this one because I think it will be tricky)
- [x] `Sphere3d` (likely similar to `Circle2d`)
- [x] `Triangle3d`
- [x] `Vector3d`

## Subtasks

- [x] Update docs/examples
- [x] Update README
- [x] Add units-related functions: `at`, `at_`, `per` etc.
- [x] Ensure `Frame2d`/`Frame3d` use `localCoordinates` and `globalCoordinates` type variable names consistently
- [x] Ensure `SketchPlane3d` uses `coordinates2d` and `coordinates3d` type variable names consistently
- [x] Tighten datum-related units type restrictions in `Vector#d` modules

**Comment by ianmackenzie** [comment]
I think this is now done! Just doing a final pass of the docs/API...
